version: '3.8'

services:
  bandit:
    build: ./main1
    container_name: bandit_service
    ports:
      - "8000:8000"
    restart: always
    networks:
      - elk-network

  speciality:
    build: ./main2
    container_name: speciality_service
    ports:
      - "8082:5000"
    restart: always
    networks:
      - elk-network

  frontend:
    build: .
    container_name: frontend_app
    ports:
      - "5001:5001"
    depends_on:
      - bandit
      - speciality
    volumes:
      - app_logs:/app/logs # Mount the named volume for logs
    networks:
      - elk-network
    restart: always

volumes:
  app_logs: # Define the named volume for application logs

networks:
  elk-network:
    external: true # Referencing the network created by the ELK docker-compose
