filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log

processors:
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  # username and password are no longer required
  # username: "elastic" 
  # password: ""

# Optional: Prevents Filebeat from failing if it checks for X-Pack features
setup.ilm.enabled: false
